// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package errorpb

import (
	jsonpb "github.com/golang/protobuf/jsonpb"
)

var (
	CodeMarshaler   = &jsonpb.Marshaler{}
	CodeUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
