// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package errorpb

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using ErrMsg within kubernetes types, where deepcopy-gen is used.
func (in *ErrMsg) DeepCopyInto(out *ErrMsg) {
	p := proto.Clone(in).(*ErrMsg)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrMsg. Required by controller-gen.
func (in *ErrMsg) DeepCopy() *ErrMsg {
	if in == nil {
		return nil
	}
	out := new(ErrMsg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ErrMsg. Required by controller-gen.
func (in *ErrMsg) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ErrCode within kubernetes types, where deepcopy-gen is used.
func (in *ErrCode) DeepCopyInto(out *ErrCode) {
	p := proto.Clone(in).(*ErrCode)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrCode. Required by controller-gen.
func (in *ErrCode) DeepCopy() *ErrCode {
	if in == nil {
		return nil
	}
	out := new(ErrCode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ErrCode. Required by controller-gen.
func (in *ErrCode) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ErrTrace within kubernetes types, where deepcopy-gen is used.
func (in *ErrTrace) DeepCopyInto(out *ErrTrace) {
	p := proto.Clone(in).(*ErrTrace)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrTrace. Required by controller-gen.
func (in *ErrTrace) DeepCopy() *ErrTrace {
	if in == nil {
		return nil
	}
	out := new(ErrTrace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ErrTrace. Required by controller-gen.
func (in *ErrTrace) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Error within kubernetes types, where deepcopy-gen is used.
func (in *Error) DeepCopyInto(out *Error) {
	p := proto.Clone(in).(*Error)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Error. Required by controller-gen.
func (in *Error) DeepCopy() *Error {
	if in == nil {
		return nil
	}
	out := new(Error)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Error. Required by controller-gen.
func (in *Error) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
