// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package errorpb

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Options
func (this *Options) MarshalJSON() ([]byte, error) {
	str, err := OptionsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Options
func (this *Options) UnmarshalJSON(b []byte) error {
	return OptionsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Fields
func (this *Fields) MarshalJSON() ([]byte, error) {
	str, err := OptionsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Fields
func (this *Fields) UnmarshalJSON(b []byte) error {
	return OptionsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	OptionsMarshaler   = &jsonpb.Marshaler{}
	OptionsUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
