syntax = "proto3";

package errors;

import "errorpb/code.proto";
import "google/protobuf/descriptor.proto";

option go_package = "github.com/pubgo/funk/v2/proto/errorpb;errorpb";

message Options {
  // gen 是否生成 error code
  bool gen = 1;

  // default_code 默认的 error code, 可能是 Internal
  Code default_code = 2;

  // name 是生成的 error code 的变量名前缀
  // 如果 name = Test, 那么 生成的 error code 变量名可能为 `TestErrCodeNotFound`
  string name = 3;
}

message Fields {
  Code code = 1;
  string msg = 2;
  string name = 3;
}

extend google.protobuf.EnumValueOptions {
  Fields field = 100002;
}

extend google.protobuf.EnumOptions {
  Options opts = 100001;
}
