version: 2

project_name: funk

release:
  prerelease: auto
  name_template: "v{{ .Version }}"

changelog:
  disable: true

builds:
  - main: ./cmds/protoc-gen-go-errors2/main.go
    id: protoc-gen-go-errors
    binary: protoc-gen-go-errors
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - main: ./cmds/protoc-gen-go-enum2/main.go
    id: protoc-gen-go-enum
    binary: protoc-gen-go-enum
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format: binary

checksum:
  name_template: "funk_{{ .Version }}_checksums.txt"
