// Code generated by protoc-gen-lava-errors. DO NOT EDIT.
// versions:
// - protoc-gen-lava-errors v0.0.4
// - protoc                 v3.19.4
// source: testcodepb/test.proto

package testcodepb

import (
	errors "github.com/pubgo/funk/errors"
	errorpb "github.com/pubgo/funk/proto/errorpb"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

var ErrCodeOK = errors.NewCode(errorpb.Code_OK).SetStatus("demo.test.v1.code.ok").SetReason("ok")
var ErrCodeNotFound = errors.NewCode(errorpb.Code_NotFound).SetStatus("demo.test.v1.code.not_found").SetReason("NotFound 找不到")
var ErrCodeUnknown = errors.NewCode(errorpb.Code_NotFound).SetStatus("demo.test.v1.code.unknown").SetReason("Unknown 未知")
var ErrCodeDbConn = errors.NewCode(errorpb.Code_Internal).SetStatus("demo.test.v1.code.db_conn").SetReason("db connect error")
