// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package testcodepb

import (
	jsonpb "github.com/golang/protobuf/jsonpb"
)

var (
	TestMarshaler   = &jsonpb.Marshaler{}
	TestUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
