// Code generated by protoc-gen-go-sql. DO NOT EDIT.
// versions:
// - protoc-gen-go-enum v0.0.2
// - protoc                 v4.25.3
// source: testcodepb/test.proto

package testcodepb

import grpc "google.golang.org/grpc"

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

func CodeValues() []string {
	return []string{"OK", "NotFound", "Unknown", "DbConn", "UnknownCode", "CustomCode"}
}

func CodeDecode(name string) Code {
	return Code(Code_value[name])
}

func User_Role_TypeValues() []string {
	return []string{"tenant", "guard", "manager", "admin"}
}

func User_Role_TypeDecode(name string) User_Role_Type {
	return User_Role_Type(User_Role_Type_value[name])
}
