// Code generated by protoc-gen-lava-errors. DO NOT EDIT.
// versions:
// - protoc-gen-lava-errors v0.0.2
// - protoc                 v3.19.4
// source: proto/testcodepb/test.proto

package testcodepb

import (
	errors "github.com/pubgo/funk/errors"
	"github.com/pubgo/funk/proto/errorpb"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

var ErrTestOK = errors.WrapBizCode(errors.WrapReason(errors.New("ok"), "ok"), "demo.test.v1.test.ok")
var ErrTestNotFound = errors.NewCode(errorpb.Code_NotFound).SetName("demo.test.v1.test.not_found").SetReason("NotFound 找不到").SetStatus(1000)
var ErrTestUnknown = errors.WrapBizCode(errors.WrapReason(errors.New("Unknown 未知"), "Unknown 未知"), "demo.test.v1.test.unknown")
var ErrTestDbConn = errors.WrapBizCode(errors.WrapReason(errors.New("db connect error"), "db connect error"), "demo.test.v1.test.db_conn")
