jobs:
  # stream name: stream config
  streams:
    gid:
      storage: "file"
      subjects: ["gid.>"]
  consumers:
#    job name: job config
    gid:
      - consumer: "test:gid"
        stream: "gid"
        subjects: "gid.proxy.exec"
        job:
          timeout: "1m"
          max_retries: 10
