// Code generated by protoc-gen-lava-errors. DO NOT EDIT.
// versions:
// - protoc-gen-lava-errors v0.0.3
// - protoc                 v3.19.4
// source: testcodepb/test.proto

package testcodepb

import (
	errors "github.com/pubgo/funk/errors"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

var ErrCodeOK = errors.WrapBizCode(errors.WrapReason(errors.New("ok"), "ok"), "demo.test.v1.code.ok")
var ErrCodeNotFound = errors.WrapBizCode(errors.WrapReason(errors.New("NotFound 找不到"), "NotFound 找不到"), "demo.test.v1.code.not_found")
var ErrCodeUnknown = errors.WrapBizCode(errors.WrapReason(errors.New("Unknown 未知"), "Unknown 未知"), "demo.test.v1.code.unknown")
var ErrCodeDbConn = errors.WrapBizCode(errors.WrapReason(errors.New("db connect error"), "db connect error"), "demo.test.v1.code.db_conn")
