// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package commonpb

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using PageRequest within kubernetes types, where deepcopy-gen is used.
func (in *PageRequest) DeepCopyInto(out *PageRequest) {
	p := proto.Clone(in).(*PageRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageRequest. Required by controller-gen.
func (in *PageRequest) DeepCopy() *PageRequest {
	if in == nil {
		return nil
	}
	out := new(PageRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new PageRequest. Required by controller-gen.
func (in *PageRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
