// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package commonpb

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for PageRequest
func (this *PageRequest) MarshalJSON() ([]byte, error) {
	str, err := PageMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PageRequest
func (this *PageRequest) UnmarshalJSON(b []byte) error {
	return PageUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	PageMarshaler   = &jsonpb.Marshaler{}
	PageUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
