// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package commonpb

import (
	jsonpb "github.com/golang/protobuf/jsonpb"
)

var (
	RequestInfoMarshaler   = &jsonpb.Marshaler{}
	RequestInfoUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
