// Code generated by protoc-gen-go-sql. DO NOT EDIT.
// versions:
// - protoc-gen-go-enum v0.0.2
// - protoc                 v5.28.2
// source: commonpb/resource.proto

package commonpb

import grpc "google.golang.org/grpc"

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

func VISIABLE_MODEValues() []string {
	return []string{"NAMESPACE", "DOMAIN", "GLOBAL"}
}

func VISIABLE_MODEDecode(name string) VISIABLE_MODE {
	return VISIABLE_MODE(VISIABLE_MODE_value[name])
}
