// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package commonpb

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Response
func (this *Response) MarshalJSON() ([]byte, error) {
	str, err := ResponseMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Response
func (this *Response) UnmarshalJSON(b []byte) error {
	return ResponseUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ResponseMarshaler   = &jsonpb.Marshaler{}
	ResponseUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
