// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package commonpb

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Response within kubernetes types, where deepcopy-gen is used.
func (in *Response) DeepCopyInto(out *Response) {
	p := proto.Clone(in).(*Response)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Response. Required by controller-gen.
func (in *Response) DeepCopy() *Response {
	if in == nil {
		return nil
	}
	out := new(Response)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Response. Required by controller-gen.
func (in *Response) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
