// Code generated by protoc-gen-go-cloudevent. DO NOT EDIT.
// Versions:
//   - protoc-gen-go-cloudevent v0.0.5
//   - protoc               v6.33.4
// source: demo.proto

package demopb

import (
	"context"
	v2 "github.com/pubgo/funk/v2"
	cloudevent "github.com/pubgo/funk/v2/component/cloudevent"
	result "github.com/pubgo/funk/v2/result"
)

const DemoCloudEventJobKey = "demo"

// HelloExecCloudEventSubjectKey /demo.cloudevent.v1.DemoInnerService/HelloExec
const HelloExecCloudEventSubjectKey = "demo.hello.exec"

type DemoInnerServiceCloudEvent struct {
	OnHelloExec func(ctx context.Context, req *HelloExecReq) error
}

func RegisterDemoInnerServiceCloudEvent(jobCli *cloudevent.Client, event DemoInnerServiceCloudEvent, opts ...cloudevent.RegisterOpt) {
	if event.OnHelloExec != nil {
		cloudevent.RegisterJobHandler(jobCli, DemoCloudEventJobKey, HelloExecCloudEventSubjectKey, event.OnHelloExec, opts...)
	}

}

type DemoInnerServiceCloudEventPublisher struct {
	Client       *cloudevent.Client
	Opt          cloudevent.PubOpt
	Interceptors []cloudevent.PubInterceptor
}

func (a DemoInnerServiceCloudEventPublisher) PushHelloExecEvent(ctx context.Context, req *HelloExecReq, opts ...cloudevent.PubOpt) result.Result[*cloudevent.PubAckInfo] {
	return a.Client.Publish(ctx, HelloExecCloudEventSubjectKey, req, a.Interceptors, v2.AppendOf(a.Opt, opts...)...)
}
