package docs

// https://github.com/duke-git/lancet
// https://github.com/samber/lo
// https://github.com/rbrahul/gofp
// https://github.com/ginkgoch/godash
// https://github.com/mailgun/holster
// https://github.com/go4org/go4
// https://github.com/kubernetes/kubernetes/tree/master/pkg/util
// https://github.com/gookit/goutil
// https://github.com/zyedidia/generic
// https://github.com/mattn/go-generics-example
// https://github.com/makiuchi-d/linq
// https://github.com/mikhailswift/go-collections
// https://github.com/deckarep/golang-set
// https://github.com/genkami/dogs
// https://github.com/life4/genesis
// https://github.com/yoyofx/glinq
// https://github.com/esimov/gogu
// https://github.com/duke-git/lancet
// https://github.com/tikafog/of
// https://github.com/mcuadros/go-defaults
// https://github.com/btcsuite/btcd/tree/master/btcutil
// https://github.com/btcsuite/btcd/tree/master/btcutil/base58
// https://github.com/btcsuite/btcd/tree/master/btcutil/bech32
// https://github.com/btcsuite/btcd/tree/master/btcutil/hdkeychain
