name: Lint & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Go Lint Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/golangci-lint/
          key: go-lint-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-lint-cache-${{ runner.os }}-

      - name: Go Mod Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
          key: go-mod-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-cache-${{ runner.os }}-

      - name: Debug Cache Path
        run: |
          ls -la ~/.cache/golangci-lint/ || echo "golangci cache path does not exist"
          ls -la ~/.cache/go-build || echo "go-build cache path does not exist"

      - name: Check go mod
        run: |
          go env
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.0
          install-mode: cache
          args: --out-format=colored-line-number --timeout=10m --new-from-rev=HEAD~1 --config=./.golangci.yml --verbose --print-issued-lines
          skip-cache: false
        env:
          GOLANGCI_LINT_CACHE: go-lint-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}

